server:
  port: 9001

spring:
  application:
    name: dhr-ms-query
    index: 0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/
  instance:
    prefer-ip-address: true
